spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/greetings_db
        username: postgres
        password: secure123!
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        format-sql: true
